### ISSUE TITLE
Building library

### ISSUE THREAD

**Issue by mihaelveber** [bennycode/trading-signals#101]
Hi,

I am new to node world. How could i build library from source, that i can use.
I tried building and got error
$ yarn clean && yarn build
$ rimraf .nyc_output coverage dist
$ tsc
../node_modules/@types/node/ts3.2/index.d.ts:19:22 - error TS6053: File '/Users/mihaelv/node_modules/@types/node/ts3.2/util.d.ts' not found.

19 /// <reference path="util.d.ts" />
                        ~~~~~~~~~
Than you in advance for answering

**Comment by bennyn** [comment]
Hi @mihaelveber, you only need two commands to build this project:

```
yarn install
yarn dist
```

If this does not work, then there is a problem with your local development setup. Which version of Node.js and Yarn are you using?
