### ISSUE TITLE
Please add TD Sequential indicator

### ISSUE THREAD

**Issue by xwartz** [bennycode/trading-signals#206]
The Tom Demark Sequential is a very popular indicator yet there are not libraries available for it in TS.

### Strategy
![image](https://user-images.githubusercontent.com/4149827/112425310-cff92f80-8d70-11eb-8fe3-64d28772a992.png)
- Buy Strategy
the trigger to buy ->
When you see 9 consecutive closes “lower” than the close 4 bars prior.
An ideal buy is when the low of bars 6 and 7 in the count are exceeded by the low of bars 8 or 9.

- Sell Strategy
trigger to sell ->
When you see 9 consecutive closes “higher” than the close 4 candles prior.
An ideal sell is when the the high of bars 6 and 7 in the count are exceeded by the high of bars 8 or 9.

### Available in Python
https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/TDSequentialStrategy.py

### Source
- https://hackernoon.com/how-to-buy-sell-cryptocurrency-with-number-indicator-td-sequential-5af46f0ebce1
- http://practicaltechnicalanalysis.blogspot.com/2013/01/tom-demark-sequential.html
- https://www.tradingview.com/chart/BTCUSD/2MJxxId6-Tom-Demark-Sequential-T-D-Sequential/

**Comment by bennycode** [comment]
Hi @xwartz and thank you for your detailed description of Tom Demark's Sequential Indicator. I will have a look at it. In the meantime, you can checkout this JavaScript implementation: https://github.com/ourarash/tdsequential

**Comment by bennycode** [comment]
I am keeping track of the ticket in [Backlog](https://github.com/bennycode/trading-signals/projects/1) project.
