### ISSUE TITLE
How to macd

### ISSUE THREAD

**Issue by Mangdar** [bennycode/trading-signals#225]
How to macd?

**Comment by bennycode** [comment]
Hi. I recommend you to start your journey from here: https://www.investopedia.com/terms/m/macd.asp

**Comment by Mangdar** [comment]
i mean how to put value to macd

**Comment by bennycode** [comment]
You can see that in the test files: https://github.com/bennycode/trading-signals/blob/v1.6.1/src/MACD/MACD.test.ts
