### ISSUE TITLE
The RSI calculation fails with a certain dataset

### ISSUE THREAD

**Issue by matiasdc1** [bennycode/trading-signals#271]
I am trying to figure out why I cannot get the RSI to work with one certain dataset in JSON.
As a reference I tried the RSI with multiple datasets and all work great, it is just this one that does not seem to work. I debugged for a while and cant find the answer.

```
const calculateRSI = data => {
  
  const rsiData = data.map((dataPoint, index) => {
    if (index < 14) {
      return {
        rsi: null,
        price: dataPoint.price,
        date: dataPoint.date,
      }
    }

    let rsi = new RSI(14)
    for (let i = 0; i < 15; i++) {
      rsi.update(data[index - i].price)
    }

    const result = parseFloat(rsi.getResult().valueOf())
    return {
      rsi: result,
      price: dataPoint.price,
      date: dataPoint.date,
    }
  })
  
  return rsiData
}
```

I execute the function as follows:

```
const { RSI } = require('trading-signals')

const weeklyData = require('./weeklyData.json')
const rsi = calculateRSI(weeklyData)
````

I get the following error for the weeklyData: 

```
NotEnoughDataError: Not enough data
```

This happens exactly at position 139 of the weekly array.
This does not happen with the dailyData array, which has exactly the same structure.

Any ideas what is going on?
I uploaded the json files in txt format as reference.

Thank you in advance.

[dailyData.txt](https://github.com/bennycode/trading-signals/files/6778927/dailyData.txt)
[weeklyData.txt](https://github.com/bennycode/trading-signals/files/6778928/weeklyData.txt)

**Comment by bennycode** [comment]
Hi @matiasdc1, the `NotEnoughDataError` is thrown when you are not feeding enough data to the `RSI` instance. With `new RSI(14)` you have to call `rsi.update` at least 14 times before you can query `rsi.getResult()`.
