### ISSUE TITLE
Add caching and fallback capabilities

### ISSUE THREAD

**Issue by lei1996** [bennycode/trading-signals#304]
For example, for the current 15 minute K-line, the data is changed, and can only be updated at the end of the current 15 minutes. How to change the newly added K-line without changing the original data set.
![image](https://user-images.githubusercontent.com/19546371/130901835-99b20a17-ff6c-4133-a803-d321f02d5c56.png)

**Comment by bennycode** [comment]
Hi @lei1996. Which indicator are you using? If I understand you correctly, you want to change the last value that you have passed to an indicator's `update` method. Am I right?

**Comment by lei1996** [comment]
> Hi @lei1996. Which indicator are you using? If I understand you correctly, you want to change the last value that you have passed to an indicator's `update` method. Am I right?

Yes, I used a combination of RSI and MACD indicators
I have solved this problem, that is, every time I generate a K-line, I new instance again
Although this will cause double counting

**Comment by bennycode** [comment]
Happy that you found a workaround! I want to keep this library here to its fundamentals which is doing the calculations for technical indicators. Caching and fallback capabilities should be implemented in the applications that make use of these indicators, so you did everything right. 👍
