### ISSUE TITLE
Add rxjs custom operator support.

### ISSUE THREAD

**Issue by lei1996** [bennycode/trading-signals#363]
example:
    
![image](https://user-images.githubusercontent.com/19546371/141815586-d7c26e1e-e7ca-4562-ad72-4389298a9729.png)

 how to use:
    
![image](https://user-images.githubusercontent.com/19546371/141815741-55f01797-e264-4b11-8700-be7bce055778.png)

**Comment by bennycode** [comment]
Hi @lei1996, do I have to add the [RxJS](https://rxjs.dev/guide/overview) dependency in order to provide this for you?

**Comment by lei1996** [comment]
I only wrote an example of MACD, which is not abstracted into all indicators.
My idea is ： defaultMacdFactory -> all indicator Factory

**Comment by lei1996** [comment]
> 嗨@lei1996，我是否必须添加[RxJS](https://rxjs.dev/guide/overview)依赖项才能为您提供这个？

Yes, I think we can create a new extension library

**Comment by bennycode** [comment]
Cool but I haven't worked with RxJS before. Would you mind doing this?

**Comment by lei1996** [comment]
> 很酷，但我以前没有使用过 RxJS。你介意这样做吗？

Okay, I will try to do this.

**Comment by bennycode** [comment]
Great! Let me know if you need help. 🙂

**Comment by lei1996** [comment]
Hi @bennycode , I create a new project in https://github.com/lei1996/rxjs-trading-signals.
