### ISSUE TITLE
Please Add EMA-open EMA - high  EMA-low available  like trading view charts....

### ISSUE THREAD

**Issue by dileepbolisetti** [bennycode/trading-signals#376]

**Comment by bennycode** [comment]
Hi @dileepbolisetti, can you give me a little more context here? You can create multiple EMAs with my library and update these with different value (`high`, `low`, ...) through the `update` method. That will solve your use-case.

**Comment by dileepbolisetti** [comment]
hi @bennycode  thanks for the reply, I'll look into the ReadMe file again...
