### ISSUE TITLE
Indicator Bollinger Bands Width (BBW)

### ISSUE THREAD

**Issue by domoskanonos** [bennycode/trading-signals#377]
Hello, first of all I want to tell you that I think this project is great.
Thanks for the implementation.

My Question:

Would it be possible to implement the Bollinger Bands Width (BBW) indicator?
Bollinger Bands Width = (Upper Band - Lower Band) / Middle Band

https://www.tradingview.com/support/solutions/43000501972-bollinger-bands-width-bbw/

**Comment by bennycode** [comment]
Hi @domoskanonos. It seems to be very easy to implement BBW. Can you please provide some sample input data and expected output so the implementation can be verified?

**Comment by domoskanonos** [comment]
it's simple, i use your BollingerBand Indicator and his results:

const bb = new BollingerBands(22, 2)

[some data].forEach(
      (price: Big) => {
        bb.update(price)
      }
    )

    const bbResult: BandsResult = bb.getResult()
    const bbw: number = bbResult.upper
      .minus(bbResult.lower)
      .div(bbResult.middle)
      .toNumber()

i think you can extend your bollingerband indicator. i can try it and create pull request ?

**Comment by bennycode** [comment]
BBW should become a new class which accepts the same params in the constructor as BB and constructs a BB within.

I need to get the candle data, BB results and BBW results as shown here to validate the implementation:

![image](https://user-images.githubusercontent.com/469989/146057716-008db916-c1bc-44f4-87ef-37122928ac5d.png)

In the screenshot we can see a candle with opening price of 66.25 and closing price of 65.77. We can also see a BB with an interval of 20 accepting the closing prices. We see also the BBW result of being 0.19.

Is there a way to get all the candles, BB results and BBW results from that embedded graph or would I need to copy them manually in order to use these values for testing my implementation?

**Comment by domoskanonos** [comment]
hi, i will send you test data tomorrow ok ?

by the way, i'm currently using your indicators in a bot of mine
https://github.com/domoskanonos/ftx-bot

have you ever thought about creating a bot?

I can keep you up to date if the bot is working. :-)



Dominik Bruhn
Holzwickeder Straße 109c
44309 Dortmund

Telefon: +49-152- 05248862


Am Di., 14. Dez. 2021 um 19:28 Uhr schrieb Benny Neugebauer <
***@***.***>:

**Comment by domoskanonos** [comment]
current price: 1.248715, Bollinger Band Width: UNSTABLE
current price: 1.248045, Bollinger Band Width: UNSTABLE
current price: 1.24946, Bollinger Band Width: UNSTABLE
current price: 1.248275, Bollinger Band Width: UNSTABLE
current price: 1.24668, Bollinger Band Width: UNSTABLE
current price: 1.24841, Bollinger Band Width: UNSTABLE
current price: 1.247435, Bollinger Band Width: UNSTABLE
current price: 1.249415, Bollinger Band Width: UNSTABLE
current price: 1.248565, Bollinger Band Width: UNSTABLE
current price: 1.250585, Bollinger Band Width: UNSTABLE
current price: 1.251275, Bollinger Band Width: UNSTABLE
current price: 1.251295, Bollinger Band Width: UNSTABLE
current price: 1.25242, Bollinger Band Width: UNSTABLE
current price: 1.25092, Bollinger Band Width: UNSTABLE
current price: 1.2525, Bollinger Band Width: UNSTABLE
current price: 1.25405, Bollinger Band Width: UNSTABLE
current price: 1.2472, Bollinger Band Width: UNSTABLE
current price: 1.24341, Bollinger Band Width: UNSTABLE
current price: 1.247165, Bollinger Band Width: UNSTABLE
current price: 1.25258, Bollinger Band Width: UNSTABLE
current price: 1.254785, Bollinger Band Width: UNSTABLE
current price: 1.258575, Bollinger Band Width: 0.010267476959998535
current price: 1.25411, Bollinger Band Width: 0.010557127030897548
current price: 1.256915, Bollinger Band Width: 0.011291149165541175
current price: 1.2519, Bollinger Band Width: 0.011279709247930597
current price: 1.248625, Bollinger Band Width: 0.011244936504113387
current price: 1.249475, Bollinger Band Width: 0.010910632300890023
current price: 1.24885, Bollinger Band Width: 0.010866096531465445
current price: 1.250945, Bollinger Band Width: 0.010576917228759076
current price: 1.250755, Bollinger Band Width: 0.010511030050797865
current price: 1.24447, Bollinger Band Width: 0.01131668649146281
current price: 1.243175, Bollinger Band Width: 0.012474623347408295
current price: 1.24363, Bollinger Band Width: 0.013325316540254666
current price: 1.24703, Bollinger Band Width: 0.013489142740897402
current price: 1.245785, Bollinger Band Width: 0.013698050387980087
current price: 1.244775, Bollinger Band Width: 0.01408626913606657
current price: 1.24377, Bollinger Band Width: 0.014445513200881045
current price: 1.243815, Bollinger Band Width: 0.01445603699405542
current price: 1.245255, Bollinger Band Width: 0.01460962128006866
current price: 1.245585, Bollinger Band Width: 0.01431533003319258

**Comment by domoskanonos** [comment]
have you been successful with your bot? Mine is still destroying money :-D

**Comment by bennycode** [comment]
> have you been successful with your bot? Mine is still destroying money :-D

A good trading bot helps with risk management and pulling the plug when losses become to high. 🤖

**Comment by bennycode** [comment]
I have implemented the Bollinger Bands Width (BBW) indicator with [trading-signals v3.3.0](https://www.npmjs.com/package/trading-signals/v/3.3.0). 

[My calculations](https://github.com/bennycode/trading-signals/blob/v3.3.0/src/BBW/BollingerBandsWidth.test.ts#L7-L44) correspond with the results from TradingView that you have shared. You can use the indicator the following way:

```ts
import { BollingerBands, BollingerBandsWidth } from 'trading-signals';

const bbw = new BollingerBandsWidth(new BollingerBands(20, 2));
bbw.update(1337);
```

Thank you very much for suggesting it! 👍

Best,
Benny

**Comment by domoskanonos** [comment]
Great. Thanks for the implementation!
