### ISSUE TITLE
Standard Deviations on Bollinger Bands

### ISSUE THREAD

**Issue by Smackface** [bennycode/trading-signals#453]
Good day, I just wanted to know if it would be possible to change the standard deviation on BBANDS with this library? I'm looking at the test file and it's clear that you can check to see if the standard deviation is 2, but I see no indication that this can be changed to a std dev of 1 or 3 for example, could you clarify this? I did try some testing in my application but I'm not very familiar with TS and the library to know if this is even possible.

Thanks!

**Comment by bennycode** [comment]
Hi @Smackface, it is absolutely possible to set the standard deviation multiplier yourself. Just pass it to the constructor of `BollingerBands`: https://github.com/bennycode/trading-signals/blob/v3.6.1/src/BBANDS/BollingerBands.ts#L32

**Example:**

```
import {BollingerBands} from 'trading-signals';

const deviationMultiplier = 3;
const bands = new BollingerBands(5, deviationMultiplier);
```

Best,
Benny
