### ISSUE TITLE
I rewritten the library with rxjs and found some question

### ISSUE THREAD

**Issue by lei1996** [bennycode/trading-signals#475]
example: CG.ts

<img width="556" alt="image" src="https://user-images.githubusercontent.com/19546371/178095258-a7a0fd98-a38a-42ea-b689-5fdb689533bb.png">

When I used rxjs to rewrite, I found that the correct value should be： 1.69989949327014160677
<img width="590" alt="image" src="https://user-images.githubusercontent.com/19546371/178095290-77cf3841-a8f4-4bcd-b87a-eac7744b6ee2.png">

**Comment by lei1996** [comment]
Srroy...  Why is SMA used here to calculate the average value, but the result is assigned with CG?
<img width="724" alt="image" src="https://user-images.githubusercontent.com/19546371/178095569-b663dd3a-f503-4bee-84da-1b6f79f708eb.png">

**Comment by bennycode** [comment]
Hi @lei1996, the [The CG Oscillator](https://www.mesasoftware.com/papers/TheCGOscillator.pdf) specification defines it to use "Simple Moving Average (SMA)" (see "Computing the CG" section).

**Comment by lei1996** [comment]
Thanks.  @bennycode 
I have updated the source code to GitHub, and NPM has also released the package。

github:  https://github.com/lei1996/rxjs-trading-signals
npm: https://www.npmjs.com/package/rxjs-trading-signals

There is still a lack of writing unit tests.

**Comment by lei1996** [comment]
like MACD:

before:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/19546371/178106347-5f31b872-cc5e-4fc5-9cbd-aaf29e64a4a5.png">


after:  use rxjs.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/19546371/178106290-2c97aede-9742-4865-9f44-4363a609c9ee.png">

**Comment by bennycode** [comment]
Cool, I will definitely have a look! Congratulations on releasing your package. 👍🏽
