### ISSUE TITLE
Unable to create Stoch RSI with EMA 

### ISSUE THREAD

**Issue by kingkong404** [bennycode/trading-signals#546]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/4363358/227866810-4e25ad76-cebf-4c97-9fba-c25ca6d38644.png">

  `const StochasticRSI = new FasterStochasticRSI(14, new FasterEMA(3))`

**Comment by bennycode** [comment]
Hi @kingkong404, the correct way to use it is:

```ts
const StochasticRSI = new FasterStochasticRSI(14, FasterEMA);
```

I will add this to the documentation.

Best,
Benny
