### ISSUE TITLE
DEMA performance issues

### ISSUE THREAD

**Issue by draganpodvezanec** [bennycode/trading-signals#558]
Hi, 

I'm using DEMA(1000) indicator for a 1s interval (so updating it every second).
After some time (5-10 min max), performances get sluggish, and updates don't even get solved in a second.
After restarting an app everything works again fine for some time.

Is there possibly some hidden memory leak?

Here's an example test which you can run and see how performance slowly degrades until it becomes unacceptable:

https://pastebin.com/tTtGhSDF

Thanks in advance.

**Comment by bennycode** [comment]
Hi @draganpodvezanec, thank you for taking the time to report this issue. Do you have the same problem when using `FasterDEMA`?

**Comment by draganpodvezanec** [comment]
Hi, thanks, FasterDEMA works fine.
