### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by kenchambers** [bennycode/trading-signals#582]
How can we import this library via CDN ? I am using DENO.

**Comment by bennycode** [comment]
Hey there! 👋 

Deno has native [support for importing npm packages](https://docs.deno.com/runtime/manual/node/npm_specifiers). Have you tried importing my library the following way?

```ts
import {SMA} from 'npm:trading-signals';
```

Best,
Benny

**Comment by kenchambers** [comment]
hmmmm, yah it says it does not have the export

```
error: Uncaught SyntaxError: The requested module 'npm:trading-signals' does not provide an export named 'ABANDS'
  ABANDS,
  ^
```

**Comment by kenchambers** [comment]
thank you for quick response!

**Comment by kenchambers** [comment]
@bennycode
I got it working, thanks so much for your help- 

Quick tangent: Have you found a lot of speed gains using deno over regular node js?

**Comment by kenchambers** [comment]
I was trying to import something that did not exist: (this worked)
```javascript
{
 SMA
} from 'npm:trading-signals'
```

**Comment by kenchambers** [comment]
I chose deno, because it seemed to have more community support. maybe I will wait a little longer until bun matures before i switch my trading stack over....
