### ISSUE TITLE
Using FasterAC

### ISSUE THREAD

**Issue by IM-001** [bennycode/trading-signals#625]
Hi there,

  Thank you very much for the great indicators library.  I am trying to use the FasterAC indicator, but I always get the error:
  
```
  NotEnoughDataError: Not enough data
    at FasterAC.getResult (Indicator.ts:67:13)
```

I am creating the indicator with a valid time serie, feeding the close values to the FasterAC (I tried many other things like feeding the high and the low...):

```
const AC = new FasterAC(shortAO, longAO, signal); // or simply const AC = new FasterAC(2, 2, 2);

timeSerie.forEach(d => {
  try {
    AC.update(d.close);
    console.log(d.close);

    try {
      const result = AC.getResult();
      console.log(result);
      seriesData.push({ value: result.high, date: d.date }); 
    } catch (error) {
      console.log(error);
      seriesData.push({ value: null, date: d.date });
    }
  } catch (error) {
    console.error("Error updating AC: ", error);
  }
});
```

Thanks for your help!

**Comment by bennycode** [comment]
Hi @IM-001, as you are create the AC using `new FasterAC(2, 2, 2)`, you have to make sure that at least 2 values are inside of AC before running `AC.getResult()`. Make sure that `AC.isStable` is `true` before executing `AC.getResult()`.

You can see that in the provided test cases: https://github.com/bennycode/trading-signals/blob/v4.0.0/src/AC/AC.test.ts#L264-L265

**Comment by IM-001** [comment]
Hi @bennycode!!  Thanks for your help!

Thanks for your help, your link gave me the right way to build my constructor.  You are right normally I would use the boolean isStable, I wanted to examine what the error was logging in this case.

So the problem is indeed my constructor:

```
// not good in previous code:
AC.update(d.close);

// Instead we need to feed it with a high low object:
const input = { high: d.high, low: d.low };

try {  
  AC.update(input);
```

Many thanks and have a great day!

**Comment by bennycode** [comment]
Happy this worked out for you! Wishing you all the best and please reach out if you need further help. 👍
