### ISSUE TITLE
I want to become a sponsor to this project

### ISSUE THREAD

**Issue by luxsush** [bennycode/trading-signals#643]
How can I become a sponsor to this project

**Comment by bennycode** [comment]
Hi @luxsush, would you like to make a donation?

**Comment by luxsush** [comment]
Yes.

**Comment by luxsush** [comment]
Also, can we call anytime at your convenience?

**Comment by bennycode** [comment]
I am currently on vacation but available next week. You can add me on Discord: `@bennycode`

**Comment by luxsush** [comment]
Discord request sent from gcadmin

**Comment by bennycode** [comment]
Great, let's continue on Discord. And thanks for the connection! 🙌
