### ISSUE TITLE
How can I use it with the nodejs require?

### ISSUE THREAD

**Issue by zigzag-way** [bennycode/trading-signals#644]
How can I use it with the classic nodejs require manner?

I want to use it like this:
const { RSI } = require('trading-signals');

Is it possible? If not, then what do you recommend?

**Comment by dtmrc** [comment]
having similar issues.. i'm using typescript, with my tsconfig as such:

```js
{
    "compilerOptions": {
        "target": "es2016",
        "moduleDetection": "auto",
         "module": "CommonJS",
         "esModuleInterop": true,
    }
}
```

receiving error when trying to `import * as tradingsignals from 'trading-signals'`

```
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/trading-signals/dist/index.js from index.ts not supported.
{
    code: 'ERR_REQUIRE_ESM'
}
```

**Comment by bennycode** [comment]
Do you get the same errors when using v3.7.0?

**Comment by mightyplow** [comment]
> Do you get the same errors when using v3.7.0?

No. 3.7 works just fine. Only having this issue with the latest version.

**Comment by bennycode** [comment]
Version 4 is based on ECMAScript modules and doesn't work with the `require` syntax. Here is the reason why: https://typescript.tv/new-features/what-are-ecmascript-modules/ - Please use v3.x if you want to use CommonJS/require syntax.

**Comment by bennycode** [comment]
@zigzag-way & @mightyplow: I have some great news for you! With trading-signals v6 you can import the package also as CJS module:

```ts
const {Big, SMA} = require('trading-signals');
```
